### ISSUE TITLE
Add average spend statistics to Analytics page.

### ISSUE THREAD

**Issue by Andze** [RaymondKirk/monzoweb#5]
Requires prerequisite Analytics page to have been created, Add average spend statistics:

- Overall average spend
- Highest on average spend 
- Lowest on average spend

**Comment by robcalcroft** [comment]
Hey once you're done with this would be happy to take a look and merge into https://github.com/robcalcroft/monzoweb 😄

**Comment by RaymondKirk** [comment]
We're doing this for our group project (University of Lincoln - Software Engineering), and will submit a pull request to you when we are done!

**Comment by robcalcroft** [comment]
Ahh awesome, look forward to seeing it 👍
